name: Release Please

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      releaseAs:
        description: 'Release as version'
        required: true
        type: string

permissions:
  contents: write
  id-token: write
  packages: write
  pull-requests: write

jobs:
  release-please:
    uses: voxpelli/ghatemplates/.github/workflows/release-please.yml@main
    secrets: inherit
    with:
      releaseAs: ${{ inputs.releaseAs }}
      packageName: "validate-conventional-commit"
      bootstrapSha: 29f9a5830a2f2ff87158591bc8ff37de38c81820
